In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

### Data loading

In [2]:
# From csv file
filepath = "./data/lr-Real-estate(1).csv"
df = pd.read_csv(filepath)
df.head()

,No,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude,Y house price of unit area
0,1,2012.917,32.0,84.87882,10,24.98298,121.54024,37.9
1,2,2012.917,19.5,306.59470,9,24.98034,121.53951,42.2
2,3,2013.583,13.3,561.98450,5,24.98746,121.54391,47.3
3,4,2013.500,13.3,561.98450,5,24.98746,121.54391,54.8
4,5,2012.833,5.0,390.56840,5,24.97937,121.54245,43.1

In [3]:
df.columns

Index(['No', 'X1 transaction date', 'X2 house age',
       'X3 distance to the nearest MRT station',
       'X4 number of convenience stores', 'X5 latitude', 'X6 longitude',
       'Y house price of unit area'],
      dtype='object')

In [4]:
# drop irrevelent columns
df = df.drop(['No'] , axis = 1)
df.head(2)

,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude,Y house price of unit area
0,2012.917,32.0,84.87882,10,24.98298,121.54024,37.9
1,2012.917,19.5,306.59470,9,24.98034,121.53951,42.2

In [5]:
# rename columns
df = df.rename(
    columns = {
        'X1 transaction date':'date',
        'X2 house age':'house age',
        'X3 distance to the nearest MRT station':'dist-nearest station',
        'X4 number of convenience stores' :'num stores',
        'X5 latitude':'lat',
        'X6 longitude':'lon',
        'Y house price of unit area' :'house price'
    }
)
df.head(2)

,date,house age,dist-nearest station,num stores,lat,lon,house price
0,2012.917,32.0,84.87882,10,24.98298,121.54024,37.9
1,2012.917,19.5,306.59470,9,24.98034,121.53951,42.2

In [6]:
df = df.drop(['date'], axis = 1)

In [7]:
df.shape # (number of records, number of features)

(414, 6)

In [8]:
df.isna().sum()

house age               0
dist-nearest station    0
num stores              0
lat                     0
lon                     0
house price             0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 414 entries, 0 to 413
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   house age             414 non-null    float64
 1   dist-nearest station  414 non-null    float64
 2   num stores            414 non-null    int64
 3   lat                   414 non-null    float64
 4   lon                   414 non-null    float64
 5   house price           414 non-null    float64
dtypes: float64(5), int64(1)
memory usage: 19.5 KB

In [11]:
df.describe()

,house age,dist-nearest station,num stores,lat,lon,house price
count,414.000000,414.000000,414.000000,414.000000,414.000000,414.000000
mean,17.712560,1083.885689,4.094203,24.969030,121.533361,37.980193
std,11.392485,1262.109595,2.945562,0.012410,0.015347,13.606488
min,0.000000,23.382840,0.000000,24.932070,121.473530,7.600000
25%,9.025000,289.324800,1.000000,24.963000,121.528085,27.700000
50%,16.100000,492.231300,4.000000,24.971100,121.538630,38.450000
75%,28.150000,1454.279000,6.000000,24.977455,121.543305,46.600000
max,43.800000,6488.021000,10.000000,25.014590,121.566270,117.500000

In [12]:
# independent and dependent feature test
X = df.drop(['house price'], axis = 1)
y = df['house price']

In [13]:
X.shape, y.shape

((414, 5), (414,))

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    train_size=0.8,
    random_state=42
    )
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)
X_train.head(3)

(331, 5) (83, 5) (331,) (83,)

     house age  dist-nearest station  num stores       lat        lon
192       43.8              57.58945           7  24.96750  121.54069
234        8.0            2216.61200           4  24.96007  121.51361
5          7.1            2175.03000           3  24.96305  121.51254

In [15]:
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression(n_jobs=-1)

#training
lin_reg.fit(X_train, y_train)

LinearRegression(n_jobs=-1)

In [16]:
preds = lin_reg.predict(X_test)

In [17]:
X_test.shape, y_test.shape, preds.shape

((83, 5), (83,), (83,))

In [18]:
temp = X_test.copy()
temp['y_test'] = y_test
temp['preds'] = preds
temp

,house age,dist-nearest station,num stores,lat,lon,y_test,preds
358,1.1,193.5845,6,24.96571,121.54089,45.1,47.741805
350,13.2,492.2313,5,24.96515,121.53737,42.3,41.954847
373,0.0,274.0144,1,24.97480,121.53059,52.2,44.539989
399,12.7,170.1289,1,24.97371,121.52984,37.3,41.336979
369,20.2,2185.1280,3,24.96322,121.51237,22.8,30.285480
...,...,...,...,...,...,...,...
31,29.6,769.4034,7,24.98281,121.53408,25.0,42.713577
283,33.5,1978.6710,2,24.98674,121.51844,23.5,31.929172
157,16.1,815.9314,4,24.97886,121.53464,35.6,41.893452
203,15.6,289.3248,5,24.98203,121.54348,46.1,46.068349
208,11.5,1360.1390,1,24.95204,121.54842,26.2,30.683913

In [19]:
# performance meatrics
from sklearn.metrics import (mean_squared_error, root_mean_squared_error, r2_score)

In [20]:
print(f"{mean_squared_error(y_test, preds) = }")
print(f"{root_mean_squared_error(y_test, preds) = }")
print(f"{r2_score(y_test, preds) = }")

mean_squared_error(y_test, preds) = 54.58094520086296
root_mean_squared_error(y_test, preds) = 7.387891796775516
r2_score(y_test, preds) = 0.6746481382828127

In [21]:
lin_reg.coef_

array([-2.70593236e-01, -4.55249601e-03,  1.10512079e+00,  2.36092831e+02,
       -2.39036942e+01])

In [22]:
lin_reg.get_params()

{'copy_X': True,
 'fit_intercept': True,
 'n_jobs': -1,
 'positive': False,
 'tol': 1e-06}

In [23]:
# sve to local directory
import joblib
joblib.dump(lin_reg, "./models/model_1.joblib")

['./models/model_1.joblib']

In [24]:
model = joblib.load("./models/model_1.joblib")
model.predict(X_test)

array([47.74180481, 41.95484652, 44.5399885 , 41.33697932, 30.28548   ,
       42.84474934, 45.98717123, 45.90599326, 24.78369465, 52.02068924,
       32.23880597, 34.77542016, 39.51392044, 24.90203898, 35.73984968,
       32.99552705, 41.96863217, 46.98662328, 31.50100311, 44.49258341,
        2.21362693, 33.64381059, 47.764103  , 43.56374399, 14.07301949,
       41.29883092, 14.73315281, 44.5399885 , 36.13972668, 37.76019401,
       11.66211419, 39.22848089, 37.83881729, 28.61334713, 45.93500741,
       31.52925298, 52.2101045 , 15.18188713, 46.84531477, 40.47464938,
       36.01694465, 40.58052131, 48.38869976, 39.8943259 , 42.00896517,
       48.22742934, 45.07252677, 23.5290158 , 49.9849698 , 48.13933326,
       47.74180481, 48.54209921, 40.94754085, 42.54642454, 36.38766353,
       15.15482781, 35.13348041, 36.39866246, 30.20430203, 45.90599326,
       33.69672647, 32.65567761, 15.15482781, 11.8739673 ,  8.74877596,
       33.67086991, 29.81801432, 45.24751413, 34.2425491 , 30.54861606,
       46.09153043, 35.88168944, 46.95956396, 45.3951109 , 35.70165143,
       39.53744483, 38.45558781, 40.03447874, 42.7135767 , 31.9291718 ,
       41.89345173, 46.0683492 , 30.68391268])

In [25]:
from sklearn.tree import DecisionTreeRegressor

dt = DecisionTreeRegressor(max_depth = 4, min_samples_split = 10)
dt.fit(X_train, y_train)

DecisionTreeRegressor(max_depth=4, min_samples_split=10)

In [26]:
y_pred_dt = dt.predict(X_test)

In [27]:
temp = X_test.copy()
temp['y_test'] = y_test
temp['y_pred_dt'] = y_pred_dt
temp

,house age,dist-nearest station,num stores,lat,lon,y_test,y_pred_dt
358,1.1,193.5845,6,24.96571,121.54089,45.1,47.778788
350,13.2,492.2313,5,24.96515,121.53737,42.3,39.511538
373,0.0,274.0144,1,24.97480,121.53059,52.2,54.257143
399,12.7,170.1289,1,24.97371,121.52984,37.3,44.165116
369,20.2,2185.1280,3,24.96322,121.51237,22.8,26.481818
...,...,...,...,...,...,...,...
31,29.6,769.4034,7,24.98281,121.53408,25.0,39.511538
283,33.5,1978.6710,2,24.98674,121.51844,23.5,31.888889
157,16.1,815.9314,4,24.97886,121.53464,35.6,39.511538
203,15.6,289.3248,5,24.98203,121.54348,46.1,44.165116
208,11.5,1360.1390,1,24.95204,121.54842,26.2,26.481818

In [28]:
print(f"{mean_squared_error(y_test, y_pred_dt) = }")
print(f"{root_mean_squared_error(y_test, y_pred_dt) = }")
print(f"{r2_score(y_test, y_pred_dt) = }")

mean_squared_error(y_test, y_pred_dt) = 39.72385344514003
root_mean_squared_error(y_test, y_pred_dt) = 6.30268620868436
r2_score(y_test, y_pred_dt) = 0.763209859679149

In [36]:
from sklearn.model_selection import GridSearchCV
dt_reg = DecisionTreeRegressor()

params = {
    'criterion': ['squared_error', 'friedman_mse', 'absolute_error', 'poisson'],
    'max_depth' : [4, 5, 6, 7, 8],
    'min_samples_split' : [10, 15, 20],
    'random_state' : [42]
}

dt_grid = GridSearchCV(dt_reg, param_grid = params)
dt_grid.fit(X_train, y_train)

GridSearchCV(estimator=DecisionTreeRegressor(),
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'absolute_error', 'poisson'],
                         'max_depth': [4, 5, 6, 7, 8],
                         'min_samples_split': [10, 15, 20],
                         'random_state': [42]})

In [39]:
dt_grid.best_params_

{'criterion': 'poisson',
 'max_depth': 4,
 'min_samples_split': 20,
 'random_state': 42}

In [40]:
best_dt_model = dt_grid.best_estimator_

In [41]:
y_pred_dt_grid = best_dt_model.predict(X_test)

In [42]:
print(f"{mean_squared_error(y_test, y_pred_dt_grid) = }")
print(f"{root_mean_squared_error(y_test, y_pred_dt_grid) = }")
print(f"{r2_score(y_test, y_pred_dt_grid) = }")

mean_squared_error(y_test, y_pred_dt_grid) = 41.41467011633693
root_mean_squared_error(y_test, y_pred_dt_grid) = 6.435423072054931
r2_score(y_test, y_pred_dt_grid) = 0.7531310611209359